name: auth-service
services:
  # app:
    # build: .
    # container_name: go-auth-service
    # ports: 
      # - "8080:8080"
    # volumes:
      # - .env:/app/.env
# 
    # depends_on:
      # - mongodb
      # - redis

  mongodb:
    image: mongo:latest
    volumes: 
      - .data/mongo:/data
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    volumes:
      - .data/redis:/data
    restart: always
    ports:
      - 6379:6379